var searchData=
[
  ['da_20contorna_20de_20mouriscados_0',['mourisAPIos - Unha API REST para a xestión do patrimonio da contorna de Mouriscados',['../index.html',1,'']]],
  ['de_20erros_1',['Listaxe de erros',['../md_docs_2erros.html#autotoc_md36',1,'']]],
  ['de_20imaxes_2',['Xestión e suba de imaxes',['../md_docs_2imaxe.html',1,'']]],
  ['de_20mouriscados_3',['mourisAPIos - Unha API REST para a xestión do patrimonio da contorna de Mouriscados',['../index.html',1,'']]],
  ['de_20sesións_4',['Xestión de Sesións',['../md_docs_2sesion.html',1,'']]],
  ['decorativos_5',['Motivos Decorativos',['../md_docs_2motivodecorativo.html',1,'']]],
  ['descrición_6',['Descrición',['../md_docs_2benpatrimonial.html#autotoc_md4',1,'Descrición'],['../md_docs_2benpatrimonial.html#autotoc_md11',1,'Descrición'],['../md_docs_2benpatrimonial.html#autotoc_md18',1,'Descrición'],['../md_docs_2benpatrimonial.html#autotoc_md24',1,'Descrición'],['../md_docs_2benpatrimonial.html#autotoc_md30',1,'Descrición'],['../md_docs_2escultura.html#autotoc_md41',1,'Descrición'],['../md_docs_2escultura.html#autotoc_md48',1,'Descrición'],['../md_docs_2escultura.html#autotoc_md55',1,'Descrición'],['../md_docs_2escultura.html#autotoc_md61',1,'Descrición'],['../md_docs_2escultura.html#autotoc_md67',1,'Descrición'],['../md_docs_2imaxe.html#autotoc_md74',1,'Descrición'],['../md_docs_2imaxe.html#autotoc_md81',1,'Descrición'],['../md_docs_2imaxe.html#autotoc_md86',1,'Descrición'],['../md_docs_2imaxe.html#autotoc_md91',1,'Descrición'],['../md_docs_2lapida.html#autotoc_md97',1,'Descrición'],['../md_docs_2lapida.html#autotoc_md101',1,'Descrición'],['../md_docs_2lapida.html#autotoc_md108',1,'Descrición'],['../md_docs_2lapida.html#autotoc_md115',1,'Descrición'],['../md_docs_2lapida.html#autotoc_md121',1,'Descrición'],['../md_docs_2lapida.html#autotoc_md127',1,'Descrición'],['../md_docs_2material.html#autotoc_md136',1,'Descrición'],['../md_docs_2material.html#autotoc_md143',1,'Descrición'],['../md_docs_2material.html#autotoc_md150',1,'Descrición'],['../md_docs_2material.html#autotoc_md156',1,'Descrición'],['../md_docs_2material.html#autotoc_md162',1,'Descrición'],['../md_docs_2motivodecorativo.html#autotoc_md171',1,'Descrición'],['../md_docs_2motivodecorativo.html#autotoc_md178',1,'Descrición'],['../md_docs_2motivodecorativo.html#autotoc_md185',1,'Descrición'],['../md_docs_2motivodecorativo.html#autotoc_md191',1,'Descrición'],['../md_docs_2motivodecorativo.html#autotoc_md197',1,'Descrición'],['../md_docs_2usuario.html#autotoc_md216',1,'Descrición'],['../md_docs_2usuario.html#autotoc_md223',1,'Descrición'],['../md_docs_2usuario.html#autotoc_md229',1,'Descrición'],['../md_docs_2usuario.html#autotoc_md235',1,'Descrición'],['../md_docs_2usuario.html#autotoc_md241',1,'Descrición']]],
  ['deseño_7',['Deseño',['../index.html#autotoc_md203',1,'']]],
  ['do_20patrimonio_20da_20contorna_20de_20mouriscados_8',['mourisAPIos - Unha API REST para a xestión do patrimonio da contorna de Mouriscados',['../index.html',1,'']]]
];
