var searchData=
[
  ['un_20inventario_0',['un inventario',['../md_docs_2benpatrimonial.html#autotoc_md29',1,'Eliminar un inventario'],['../md_docs_2escultura.html#autotoc_md66',1,'Eliminar un inventario'],['../md_docs_2lapida.html#autotoc_md126',1,'Eliminar un inventario'],['../md_docs_2material.html#autotoc_md161',1,'Eliminar un inventario'],['../md_docs_2motivodecorativo.html#autotoc_md196',1,'Eliminar un inventario'],['../md_docs_2usuario.html#autotoc_md240',1,'Eliminar un inventario'],['../md_docs_2benpatrimonial.html#autotoc_md23',1,'Engadir un inventario'],['../md_docs_2escultura.html#autotoc_md60',1,'Engadir un inventario'],['../md_docs_2lapida.html#autotoc_md120',1,'Engadir un inventario'],['../md_docs_2material.html#autotoc_md155',1,'Engadir un inventario'],['../md_docs_2motivodecorativo.html#autotoc_md190',1,'Engadir un inventario'],['../md_docs_2benpatrimonial.html#autotoc_md17',1,'Modificar un inventario'],['../md_docs_2escultura.html#autotoc_md54',1,'Modificar un inventario'],['../md_docs_2lapida.html#autotoc_md114',1,'Modificar un inventario'],['../md_docs_2material.html#autotoc_md149',1,'Modificar un inventario'],['../md_docs_2motivodecorativo.html#autotoc_md184',1,'Modificar un inventario']]],
  ['un_20usuario_1',['un usuario',['../md_docs_2usuario.html#autotoc_md234',1,'Engadir un usuario'],['../md_docs_2usuario.html#autotoc_md228',1,'Modificar un usuario']]],
  ['unha_20api_20rest_20para_20a_20xestión_20do_20patrimonio_20da_20contorna_20de_20mouriscados_2',['mourisAPIos - Unha API REST para a xestión do patrimonio da contorna de Mouriscados',['../index.html',1,'']]],
  ['unha_20imaxe_3',['unha imaxe',['../md_docs_2imaxe.html#autotoc_md73',1,'Buscar unha imaxe'],['../md_docs_2imaxe.html#autotoc_md90',1,'Eliminar unha imaxe'],['../md_docs_2imaxe.html#autotoc_md80',1,'Modificar unha imaxe'],['../md_docs_2imaxe.html#autotoc_md85',1,'Rexistrar unha imaxe']]],
  ['uso_4',['Uso',['../index.html#autotoc_md204',1,'']]],
  ['usuario_5',['usuario',['../md_docs_2usuario.html#autotoc_md234',1,'Engadir un usuario'],['../md_docs_2usuario.html#autotoc_md228',1,'Modificar un usuario']]],
  ['usuarios_6',['Usuarios',['../md_docs_2usuario.html',1,'']]],
  ['usuarios_7',['usuarios',['../md_docs_2usuario.html#autotoc_md222',1,'Buscar usuarios'],['../md_docs_2usuario.html#autotoc_md215',1,'Listar usuarios']]]
];
